POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2siLCJpZCI6IjY4NzJhOGRlMmUwYjhmNmRlZGZiM2Q1ZSIsImlhdCI6MTc1MjUxMzY5NCwiZXhwIjoxNzUyNTE3Mjk0fQ.1MTvjCDe9TFkkF95oVAWuSOt-_yDNX1Pri2xP2Pi6vY

{
  "title": "Test_blog123",
  "author": "Test Author123",
  "url": "Test_url",
  "likes": "2"
}
